### ISSUE TITLE
x509 > 365 days

### ISSUE THREAD

**Issue by Einstein42** [jfromaniello/selfsigned#17]
Please allow for generation of x509 certificates > 365  days. Regardless of how many days I set in the attr's the certificate is only valid for 365 days.

**Comment by jfromaniello** [comment]
Have you tried as described in the readme?:

```javascript
var pems = selfsigned.generate(attrs, { days: 365 });
console.log(pems)
```

**Comment by Einstein42** [comment]
Yes. I want days > 365 however. No matter what I enter for the days attribute, in this case I've tried 366 all the way to 3650 it always generates exactly 365.

**Comment by jfromaniello** [comment]
You must be doing something wrong, please notice that the days options goes in the second parameter.

I just tested this, here is an example:

```
» node
> var selfsigned = require('selfsigned')
> var pair = selfsigned.generate({}, {days: 10 * 365});
> fs.writeFileSync('./test.pem', pair.cert);
> process.exit(0);

 » openssl x509 -enddate -noout -in  test.pem
notAfter=Oct  7 17:11:05 2027 GMT
```

**Comment by Einstein42** [comment]
So what is wrong with this then?

`var selfsigned = require('selfsigned')
var fs = require('fs')
var attrs = [
        { name: 'commonName', value: 'blah.com'},
        { name: 'countryName', value: 'US'},
        { shortName: 'ST', value: 'California'},
        { name: 'localityName', value: 'Los Angeles'},
        { name: 'organizationName', value: 'Company'},
        { shortName: 'OU', value: 'Product'}
]
var opts = [
        { keySize: 2048 },
        { algorithm: 'sha256' },
        { days: 365 * 10 }
]
var pems = selfsigned.generate(attrs, opts)
fs.writeFileSync('polyglot.key', pems.private)
fs.writeFileSync('polyglot.crt', pems.cert)
`
$ openssl x509 -enddate -noout -in polyglot.crt                              
notAfter=Oct  9 17:38:21 2018 GMT

**Comment by Einstein42** [comment]
Holy crap, you're right. I passed in an array. My fault. Thanks. I got it.
