### ISSUE TITLE
Copyright clarification

### ISSUE THREAD

**Issue by alloy** [jfromaniello/selfsigned#28]
Hi,

I’m trying to [add this as a dependency to a project](
https://github.com/DataDog/dd-trace-js/pull/268#discussion_r21452513)3 that requires listing of all dependencies’ licenses and copyright. However, in your case I wasn’t able to find an explicit clarification of the copyright owners and for what time periods. Would you mind adding that to your project?

**Comment by jfromaniello** [comment]
Thank you , I just added the missing LICENSE file. Can you let me know if this is enough for you?

**Comment by alloy** [comment]
Thanks! I assume so, but will have to check back in with the maintainer of the other project.

**Comment by patricksmms** [comment]
Hi, I see that now you have the license file, but it seems like the version 1.10.4 was only published on GitHub. On npm the latest version is still 1.10.3, that doesn't contain the license file. Could you please publish the latest on npm?

**Comment by jfromaniello** [comment]
@patricksmms sorry about that, I just published

**Comment by patricksmms** [comment]
@jfromaniello thanks a lot!
