### ISSUE TITLE
License violation issue as dependency node-forge is now under GPL

### ISSUE THREAD

**Issue by akankshagaur** [jfromaniello/selfsigned#34]
Hi,

I am using self-signed library in my project & whitesource gave us a license violation alert as it is using node-forge which is under GPL now. Is there an alternate for the same?

Thanks
Akanksha Gaur

**Comment by akx** [comment]
node-forge 0.9.0, which this package depends on, is licensed ([here](https://github.com/digitalbazaar/forge/blob/0.9.0/LICENSE), [here](https://github.com/digitalbazaar/forge/blob/0.9.0/package.json#L53)) under _either_ BSD or GPLv2.

You may wish to raise an issue against this Whitesource tool instead.

**Comment by jfromaniello** [comment]
thank you for the clarifications
