### ISSUE TITLE
Dependency node-forge has critical security vulnerability

### ISSUE THREAD

**Issue by csvan** [jfromaniello/selfsigned#47]
node-forge  0.10.0
Severity: critical
node-forge Package for Node.js lib/debug.js set() Function Prototype Pollution Unspecified Issue - https://github.com/418sec/forge/pull/1,https://github.com/digitalbazaar/forge/issues/857,https://huntr.dev/bounties/1-npm-node-forge/

**Comment by davidlehn** [comment]
This issue is fixed in node-forge 1.0.0.
(I doubt anyone has ever used that debug API, including forge itself, so it's probably not "critical".)

**Comment by csvan** [comment]
Yea I think the classifications are weird sometimes too :-/
