### ISSUE TITLE
v1.3.0 is a breaking change via node-forge upgrade in node < 10: "ReferenceError: URLSearchParams is not defined"

### ISSUE THREAD

**Issue by billneff79** [jfromaniello/selfsigned#50]
If you are running node < 10, the upgrade to node-forge 1.x contained in selfsigned@1.3.0 produces the following error because URLSearchParams is not natively supported:

```bash
/Users/bneff/repos/blocks/node_modules/selfsigned/node_modules/node-forge/lib/log.js:305
    query = new URLSearchParams();
    ^

ReferenceError: URLSearchParams is not defined
    at Object.<anonymous> (/Users/bneff/repos/blocks/node_modules/selfsigned/node_modules/node-forge/lib/log.js:305:5)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
```

Upgrading node-forge to 1.x should have been a major change in selfsigned

**Comment by devmubeen** [comment]
Anyone checked this issue?

**Comment by reachmehere89** [comment]
Same issue we are also facing

**Comment by ahmedHusseinF** [comment]
Same issue, i think you should upgrade the `major` version not just a `patch`, because this is a breaking change in `node-forge`

**Comment by jfromaniello** [comment]
😫 my bad, ok I will publish a major version and a patch reverting the patch. Does that sounds good?

**Comment by jfromaniello** [comment]
ok, now I published:
- `selfsigned@2.0.0` (with engines node >=10) using `node-forge@^1.2`
- `selfsigned@1.10.14` which is the same than `selfsigned@1.10.12`
