### ISSUE TITLE
Type of `extensions` is not `string[]`.

### ISSUE THREAD

**Issue by hperrin** [jfromaniello/selfsigned#62]
https://github.com/jfromaniello/selfsigned/blob/b52e1f20e22c2f6a3f7d1cc4fe5c9592a3e7f217/index.d.ts#L17

This line is wrong.

**Comment by hperrin** [comment]
The `@types/selfsigned` package has `any[]` for this type:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/selfsigned/index.d.ts#L16

**Comment by hperrin** [comment]
Thanks. :)

**Comment by jfromaniello** [comment]
Thank you! published as `selfsigned@2.1.1`
